name: Prod Auto Update

on:
  workflow_dispatch:
  schedule:
    # Run workflow every 30 minutes
    - cron: "*/30 * * * *"

jobs:
  auto_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install pipenv Python dependency manager
        run: pip install pipenv

      - name: Install project dependencies
        run: pipenv install

      - name: Scrape data and update database
        id: update
        env:
          POSTGRES_DSN: ${{ secrets.POSTGRES_DSN }}
          SIS_RIN: ${{ secrets.SIS_RIN }}
          SIS_PIN: ${{ secrets.SIS_PIN }}
        run: |
          pipenv run python -m scripts.import 202101

      - name: If update fail, create issue
        if: steps.update.outcome == 'failure'
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Failed to update ${{ matrix.semester }}",
              labels: ["bug"]
            })
