name: Prod Auto Update

on:
  workflow_dispatch:
  schedule:
    # Run workflow every 30 minutes
    - cron: "*/30 * * * *"

jobs:
  auto_update:
    runs-on: ubuntu-latest

    # Run job for each semester
    strategy:
      matrix:
        semester: [202101]

    steps:
      - name: Call course update route
        id: update
        env:
          API_KEY: ${{ secrets.API_KEY }}
          URL: https://rcos-orca.herokuapp.com
          SEMESTER: ${{ matrix.semester }}
        run: |
          # Send POST request to production update route with API key in body
          curl -X POST --silent --fail $URL/$SEMESTER/sections/update?api_key=$API_KEY

      - name: If update fail, create issue
        if: ${{ failure() }}
        uses: actions/github-script@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Failed to update ${{ matrix.semester }}",
              labels: ["bug"]
            })
